## 1 Importing the libraries

In [1]:
import numpy as np # for calculations
import pandas as pd # for data manipulation

## 2 Importing the dataset

In [5]:
dataset = pd.read_csv('Data.csv')
dataset.head() # the argument in the bracket: how many rows to show

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [9]:
# method 1: find data by indexing the column
X = dataset.iloc[ :, :-1].values # from column 0 to (4)-1th column
Y = dataset.iloc[ :, 3].values # Purchased

## 3 Handling the missing data

In [12]:
from sklearn.preprocessing import Imputer
# specify what values should be the missing data
# filling the missing data with mean values
# axis = 0 for column, 1 for row
imputer = Imputer(missing_values = 'NaN', strategy='mean', axis=0)
imputer = imputer.fit(X[ :, 1:3]) # only fill numerical data
X[ :, 1:3] = imputer.transform(X[ :, 1:3])
X

/home/ranley/anaconda3/lib/python3.7/site-packages/sklearn/utils/deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

## 4 Encoding categorical data
Y stands for text data which cannot be computed easily, so we can create dummy variables for them.
### Give each country a value to represent it

In [15]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
# LabelEncoder: give each original type a numerical value to represent it
# OneHotEncoder: only one grid shows 1 in one row (one hot)
labelencoder_X = LabelEncoder()
X[ : , 0] = labelencoder_X.fit_transform(X[ : , 0])
X # 0 for France, 2 for Spain, 1 for Germany (arphabically)

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

### Creating a dummy variable

In [20]:
onehotencoder = OneHotEncoder(categorical_features=[0]) # country
X = onehotencoder.fit_transform(X).toarray()
X[0]

/home/ranley/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/home/ranley/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


array([0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 4.4e+01, 7.2e+04])

In [22]:
# deal Y from 'Yes' 'No' to numbers
labelencoder_Y = LabelEncoder()
Y = labelencoder_Y.fit_transform(Y)
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

## 5 Splitting the dataset into training and test

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split( X , Y , test_size = 0.2, random_state = 0)

## 6 Feature Scaling

In [26]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.fit_transform(X_test)